import Head from 'next/head';
import Header from './components/header';
import Link from 'next/link';
import { Home } from '@/src/pages/home';
export default function HomePage(props) {
  return <Home {...props} />;
}

//     <>
//       <Head>
//         <title>Therapy</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="bg-white h-screen">
//         <div className="flex flex-col gap-8 m-auto p-10 bg-white max-w-[90rem]">
//           <Header></Header>
// 0          <div className=" flex flex-col mt-[120px] gap-20">
//             <div className="grid grid-cols-3 gap-32">
//               <div className="col-span-1 h-[668px] bg-[#E9E6E6] flex flex-col gap-8 p-8 relative">
//                 <p className="font-bold text-lg mx-auto">Depression</p>
//                 <p className="text-lg">
//                   Depression is a mental health condition that can affect a
//                   person&apos;s mood, behavior, and overall quality of life.
//                 </p>{' '}
//                 <p className="text-lg">
//                   {' '}
//                   People with depression may feel sad, hopeless, or anxious for
//                   an extended period of time.
//                 </p>{' '}
//                 <p className="text-lg">
//                   {' '}
//                   In addition to emotional symptoms, depression can also cause
//                   physical symptoms, such as changes in appetite or sleep
//                   patterns, fatigue, and unexplained aches and pains.
//                 </p>
//                 <p className="text-lg text-blue-800 hover:underline">
//                   {' '}
//                 </p>
//                 <Link href={'/quiz/depression'} className="absolute bottom-4 left-[100px] border-[3px] rounded-lg border-black w-fit p-2">
//                   Take the quiz now
//                 </Link>
//               </div>
//               <div className="col-span-1 h-[668px] bg-[#E9E6E6] flex flex-col gap-8 p-8 relative">
//                 <p className="font-bold text-lg mx-auto">ADHD</p>
//                 <p className="text-lg">
//                   ADHD stands for Attention Deficit Hyperactivity Disorder.
//                 </p>{' '}
//                 <p className="text-lg">
//                   {' '}
//                   It&apos;s a mental health condition that affects how a person pays
//                   attention, controls their behavior, and manages their
//                   emotions.
//                 </p>{' '}
//                 <p className="text-lg">
//                   {' '}
//                   People with ADHD may have difficulty concentrating or paying
//                   attention, and may become easily distracted.
//                 </p>
//                 <p className="text-lg text-blue-800 hover:underline">
//                   {' '}
//                   {/* Know More.. */}
//                 </p>
//                 <Link href={'/quiz/ADHD'} className="absolute bottom-4 left-[100px] border-[3px] rounded-lg border-black w-fit p-2">
//                   Take the quiz now
//                 </Link>
//               </div>
//               <div className="col-span-1 h-[668px] bg-[#E9E6E6] flex flex-col gap-8 p-8 relative">
//                 <p className="font-bold text-lg mx-auto">Anxiety</p>
//                 <p className="text-lg">
//                   Anxiety is a mental health condition characterized by
//                   excessive and persistent worry, fear, or apprehension about
//                   everyday situations or events.
//                 </p>{' '}
//                 <p className="text-lg">
//                   {' '}
//                   People with anxiety may feel like they are in danger, even
//                   when there is no real threat present.
//                 </p>{' '}
//                 <p className="text-lg">
//                   {' '}
//                   Anxiety can cause physical symptoms, such as rapid heartbeat,
//                   sweating, trembling, or muscle tension.
//                 </p>
//                 <p className="text-lg text-blue-800 hover:underline">
//                   {' '}
//                   {/* Know More.. */}
//                 </p>
//                 <Link href={'/quiz/Anxiety'} className="absolute bottom-4 left-[100px] border-[3px] rounded-lg border-black w-fit p-2">
//                   Take the quiz now
//                 </Link>
//               </div>
//             </div>
//           </div>
//         </div>
//       </div>
//     </>

export async function getStaticProps() {
  const res1 = await fetch('https://therapy-mauve.vercel.app/api/quiz/ADHD');
  const ADHDQuiz = await res1.json();
  const res2 = await fetch('https://therapy-mauve.vercel.app/api/quiz/Anxiety');
  const AnxietyQuiz = await res2.json();
  const res3 = await fetch(
    'https://therapy-mauve.vercel.app/api/quiz/depression'
  );
  const depressionQuiz = await res3.json();
  return {
    props: {
      ADHDQuiz,
      AnxietyQuiz,
      depressionQuiz,
    },
  };
}
